steps:
  # Step 0: Install mysqli (php-mysql) package
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'myvm-1-nailul'
      - '--zone=asia-southeast2-a'
      - '--command=sudo apt-get update && sudo apt-get install -y mysql-server php-mysql && sudo systemctl restart apache2'
timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
